[package]
name = "time-tzdb"
version = "0.1.0"
authors = ["Jacob Pratt <open-source@jhpratt.dev>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]
